### ISSUE TITLE
list.h missing

### ISSUE THREAD

**Issue by CoderOnWinks** [ipserc/jsmnRipper#1]
Hi,

list.h is not found, is it the one header which is supplied as part of linux kernel?

**Comment by ipserc** [comment]
Hi, 

You can find it in another of my projects called list (https://github.com/ipserc/list/tree/master/Source)
For compiling jsmnRipper I have linked the lib created from "list".
Don't hesitate to ask me for any doubt

**Comment by ipserc** [comment]
Hi again,

Take a look on "jsmnGetToken" to see how you need to use "list" and "jsmnRipper" to extract tokens from a Json message.
