### ISSUE TITLE
thanks!

### ISSUE THREAD

**Issue by schui-jo** [ipserc/jsmnRipper#2]
Thanks for the work!  I had to modify jumpToTokenPos() so it would check retVal (return of nextToken()) else it would hang in the while loop on an unfound path in a call to getTokenValue().

Diff for jsmnRipper.c:
14c14,16
< #define JSMN_PARENT_LINKS
---
> #ifndef JSMN_PARENT_LINKS
>  #define JSMN_PARENT_LINKS
> #endif
166,167c168,169
< 	bool retVal = false;
< 	while (((jsmntok_t *)(*jsonToken))->start < newPosition) retVal = nextToken(jsonToken);
---
> 	bool retVal = true;
> 	while( (((jsmntok_t *)(*jsonToken))->start < newPosition) && (false != retVal) ) retVal = nextToken( jsonToken );

**Comment by ipserc** [comment]
Hi schui-jo,

Thank you very much for taking a look at the code of jsmnRipper and make the fix required.

Right now I'm involved in the deadline of a project and I haven't got enough spare time to review and include the fix, but I'll take a look at the beginning of August.

Please fell free to make any comment or improvement in the code, this is why I've put it in Git for everyone.

Best Regards

Jose Luis

**Comment by ipserc** [comment]
Finally I've got time to follow your indications and fixed jumpToTokenPos as you told me. But I've used retVal == 0 as indicator (is the same as false) only for keeping coherence with the meaning of nextToken, which returns the position in the Json string of the next token. 

Thank you very much.
